// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eTGelYwyY7tlCg_zlA_It5XE6zZjKso',
    appId: '1:794027433081:web:42a28d8ae60c543cb848a8',
    messagingSenderId: '794027433081',
    projectId: 'bloodlink-dc69c',
    authDomain: 'bloodlink-dc69c.firebaseapp.com',
    storageBucket: 'bloodlink-dc69c.firebasestorage.app',
    measurementId: 'G-B1JZ6DF6C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgH7tCDKtG8FhI0x-Bz1h69eX4ox556A',
    appId: '1:794027433081:android:440e3f89291b5991b848a8',
    messagingSenderId: '794027433081',
    projectId: 'bloodlink-dc69c',
    storageBucket: 'bloodlink-dc69c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5eTGelYwyY7tlCg_zlA_It5XE6zZjKso',
    appId: '1:794027433081:web:6fa71f60a26b0fd6b848a8',
    messagingSenderId: '794027433081',
    projectId: 'bloodlink-dc69c',
    authDomain: 'bloodlink-dc69c.firebaseapp.com',
    storageBucket: 'bloodlink-dc69c.firebasestorage.app',
    measurementId: 'G-FHYPYQVR3G',
  );
}
